name: 'Create Ansible configuration'
description: 'Create a custom Ansible configuration'
inputs:

  existing_config_file_path:
    description: 'If there is a custom Ansible config file, provide the path to it'
    required: false
  directory_path:
    description: |
      Path to the directory where Ansible config sits. 
      The directory will be created if it does not exist
    required: false
    default: 'ansible'
  config_file_name:
    description: |
      The name of the target Ansible config file.
      The file will be created in the directory pointed to by directory_path
    required: false
    default: 'ansible.cfg'
  remote_user:
    description: 'The remote user for Ansible'
    required: true
  inventory_file:
    description: 'The path to the inventory file for Ansible'
    required: false
    default: 'ansible/hosts.cfg'
  private_key_file:
    description: 'The private key for Ansible'
    required: false
  roles_path:
    description: 'The path to the folder containing Ansible roles'
    required: false
    default: 'ansible/roles'

  host_key_checking:
    description: 'The host_key_checking option for Ansible'
    required: false
    default: 'False'
  privilege_escalation:
    description: 'Whether the privilege escalation should be true or false'
    required: false
    default: 'True'
runs:
  using: 'node16'
  main: 'dist/index.js'
