name: "units-test"
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        directory_path: 'ansible'
        config_file_name: 'ansible.cfg'
        remote_user: 'ubuntu'
        inventory_file: 'ansible/hosts.cfg'
        host-key-checking: 'False'
        privilege-escalation: 'True'

    - name: list files
      run: ls

    - name: display content of ANSIBLE_CONFIG env var
      run: echo $ANSIBLE_CONFIG
